/**
 * MATLAB snippet generator for the "Show code" button.
 *
 * Mirrors `python.ts` but targets the NDI-matlab toolbox. Function
 * names map to MATLAB's `+ndi/+cloud/+api/{datasets,documents,files}`
 * packages exactly as they exist on the head of NDI-matlab.
 *
 * Output shape: ONE `.m` file as a string. A leading comment banner,
 * then one section per tool call. Sections use the MATLAB section
 * marker (`%%`) so the user can step through with "Run Section" in
 * the MATLAB editor.
 *
 * Wherever the user-side MATLAB API is uncertain (notably the
 * tabular_query and fetch_signal backends, which were added on the
 * NDI Ask backend before any user-facing wrapper landed), the
 * snippet emits a `% TODO:` comment + a placeholder call. The user
 * can refine; this is meant to be a starting point, not a 1:1
 * server replica.
 */
import type { RecordedToolCall } from './types';
import {
  formatMatlabValue,
  pickNumber,
  pickString,
  pickValue,
  serializeQueryStruct,
} from './utils';

export interface MatlabSnippetOptions {
  question?: string;
  timestamp?: string;
  chatUrl?: string;
}

/**
 * Build the leading comment banner. MATLAB doesn't have a native
 * docstring; we use a `%` comment block. The banner stays inside the
 * single-`%` zone so the editor doesn't fold it as a section.
 */
function header(opts: MatlabSnippetOptions): string {
  const now = opts.timestamp ?? new Date().toISOString();
  const lines: string[] = [
    '% NDI Ask — reproducible MATLAB snippet.',
    '%',
    '% Generated by the experimental NDI Ask chat. Each section below',
    '% mirrors a tool the assistant invoked while answering your question.',
    '% Run section-by-section to reproduce the analysis. Requires the',
    '% NDI-matlab toolbox on the MATLAB path.',
    '%',
  ];
  if (opts.question) {
    lines.push(`% Question: ${oneLine(opts.question)}`);
  }
  lines.push(`% Generated: ${now}`);
  if (opts.chatUrl) {
    lines.push(`% Chat: ${opts.chatUrl}`);
  }
  return lines.join('\n');
}

function oneLine(s: string): string {
  return s.replace(/\s+/g, ' ').trim();
}

export function generateMatlabSnippet(
  toolCalls: RecordedToolCall[],
  options: MatlabSnippetOptions = {},
): string {
  const blocks: string[] = [];
  blocks.push(header(options));

  if (toolCalls.length === 0) {
    blocks.push(
      '\n% (No tool calls were recorded for this answer — the assistant\n' +
        '% answered from prior context. Nothing to reproduce.)',
    );
    return blocks.join('\n') + '\n';
  }

  toolCalls.forEach((call, index) => {
    blocks.push(renderToolCall(call, index));
  });

  return blocks.join('\n') + '\n';
}

function renderToolCall(call: RecordedToolCall, index: number): string {
  const banner = `\n%% Step ${index + 1}: ${call.toolName}`;
  return `${banner}\n${renderToolBody(call)}`;
}

function renderToolBody(call: RecordedToolCall): string {
  const args = call.args ?? {};
  switch (call.toolName) {
    case 'list_published_datasets':
      return renderListPublishedDatasets(args);
    case 'get_dataset':
      return renderGetDataset(args);
    case 'get_dataset_summary':
      return renderGetDatasetSummary(args);
    case 'get_dataset_class_counts':
      return renderGetDatasetClassCounts(args);
    case 'get_facets':
      return renderGetFacets();
    case 'semantic_search_datasets':
      return renderSemanticSearchDatasets(args, call.result);
    case 'query_documents':
      return renderQueryDocuments(args);
    case 'ndi_query':
      return renderNdiQuery(args);
    case 'aggregate_documents':
      return renderAggregateDocuments(args);
    case 'tabular_query':
      return renderTabularQuery(args);
    case 'fetch_signal':
      return renderFetchSignal(args);
    // a834 P1 #C-1 (2026-05-14) — chart-tool snippets added below.
    case 'fetch_image':
      return renderFetchImage(args);
    case 'treatment_timeline':
      return renderTreatmentTimeline(args);
    case 'fetch_spike_summary':
      return renderFetchSpikeSummary(args);
    case 'psth':
      return renderPsth(args);
    case 'walk_provenance':
      return renderWalkProvenance(args);
    case 'lookup_ontology':
      return renderLookupOntology(args);
    default:
      return (
        `% TODO: no NDI-matlab mapping known for "${call.toolName}".\n` +
        `% Arguments captured from the chat:\n` +
        `args = ${formatMatlabValue(args)};\n`
      );
  }
}

// ── per-tool emitters ────────────────────────────────────────────────

function renderListPublishedDatasets(args: unknown): string {
  const page = pickNumber(args, 'page') ?? 1;
  const pageSize = pickNumber(args, 'pageSize') ?? 20;
  const query = pickString(args, 'query');
  // MATLAB's ndi.cloud.api.datasets.getPublished(args.page, args.pageSize)
  // accepts only page + pageSize — no `query` arg (audit 2026-05-18
  // finding A8). The chat substring-filters client-side; for MATLAB
  // we annotate so the user knows to filter the returned struct.
  const lines = [
    `% Browse the public NDI catalog (one page). All MATLAB cloud-API`,
    `% wrappers return [b, answer, ...] — capture the second LHS to`,
    `% get the data (audit 2026-05-18 findings A2/A5).`,
    `[success, published] = ndi.cloud.api.datasets.getPublished('page', ${page}, 'pageSize', ${pageSize});`,
  ];
  if (query) {
    lines.push(
      `% getPublished has no server-side text-search arg — filter client-side:`,
      `q = lower(${formatMatlabValue(query)});`,
      `matches = arrayfun(@(d) contains(lower(string(d.name)), q) || contains(lower(string(d.description)), q), published.datasets);`,
      `published.datasets = published.datasets(matches);`,
      `published.totalNumber = numel(published.datasets);`,
    );
  }
  lines.push(`fprintf('Total datasets: %d\\n', published.totalNumber);`);
  return lines.join('\n');
}

function renderGetDataset(args: unknown): string {
  const id = pickString(args, 'id') ?? '<dataset-id>';
  // getDataset returns [b, answer, apiResponse, apiURL] — single-LHS
  // capture grabs the boolean. Audit 2026-05-18 finding A2.
  return (
    `% Fetch the full record for one dataset.\n` +
    `[success, dataset] = ndi.cloud.api.datasets.getDataset(${formatMatlabValue(id)});\n` +
    `disp(dataset);`
  );
}

function renderGetDatasetSummary(args: unknown): string {
  const id = pickString(args, 'id') ?? '<dataset-id>';
  return (
    `% Fetch a compact summary for one dataset.\n` +
    `% NDI-matlab does not yet expose a dedicated summary call;\n` +
    `% use getDataset for the full record and read its count fields.\n` +
    `[success, summary] = ndi.cloud.api.datasets.getDataset(${formatMatlabValue(id)});`
  );
}

function renderGetDatasetClassCounts(args: unknown): string {
  const id = pickString(args, 'id') ?? '<dataset-id>';
  // documentClassCounts answer is {datasetId, totalDocuments, classCounts}
  // — the per-class map lives under classCounts (NOT a top-level
  // dict). Audit 2026-05-18 findings A2 + A13.
  return (
    `% Count documents per class for one dataset.\n` +
    `[success, counts] = ndi.cloud.api.documents.documentClassCounts(${formatMatlabValue(id)});\n` +
    `disp(counts.classCounts);`
  );
}

function renderGetFacets(): string {
  return (
    `% Cross-catalog facets (species / brain regions / strains).\n` +
    `% TODO: NDI-matlab does not yet wrap /api/facets; call the HTTP\n` +
    `% endpoint via webread once authentication is configured.\n` +
    `% facets = webread('https://api.ndi-cloud.com/api/facets');`
  );
}

function renderSemanticSearchDatasets(args: unknown, result: unknown): string {
  const query = pickString(args, 'query') ?? '';
  const lines = [
    `% Semantic search is not reproducible in user code — the embedding`,
    `% index lives behind the NDI Ask chat. The IDs below are what the`,
    `% chat returned for: ${oneLine(query)}`,
  ];
  const results = pickValue(result, 'results');
  if (Array.isArray(results)) {
    for (const r of results) {
      const id = pickString(r, 'id');
      const name = pickString(r, 'name');
      if (id) lines.push(`%  - ${id}${name ? ` — ${name}` : ''}`);
    }
  }
  lines.push(
    `% Use one of these IDs with ndi.cloud.api.datasets.getDataset to drill in.`,
  );
  return lines.join('\n');
}

function renderQueryDocuments(args: unknown): string {
  const datasetId = pickString(args, 'datasetId') ?? '<dataset-id>';
  const className = pickString(args, 'className') ?? 'subject';
  const limit = pickNumber(args, 'limit') ?? 10;
  // ndiqueryAll(scope, query_obj, args) — takes the query OBJECT
  // (the wrapper extracts .searchstructure internally) and returns
  // [b, answer, ...] where `answer` is a struct ARRAY of document
  // summaries {id, ndiId, name, className, datasetId}. For full
  // document bodies follow up with bulkFetch. Audit 2026-05-18
  // findings A4/A5.
  return (
    `% Pull all documents of a given class inside one dataset.\n` +
    `q = ndi.query('', 'isa', ${formatMatlabValue(className)});\n` +
    `[success, summaries] = ndi.cloud.api.documents.ndiqueryAll(${formatMatlabValue(datasetId)}, q, 'pageSize', ${limit});\n` +
    `% summaries is a struct array. For full bodies with .data:\n` +
    `%   [~, docs] = ndi.cloud.api.documents.bulkFetch(${formatMatlabValue(datasetId)}, string({summaries.id}));\n` +
    `fprintf('Found %d ${className} document(s)\\n', numel(summaries));`
  );
}

function renderNdiQuery(args: unknown): string {
  const scope = pickString(args, 'scope') ?? 'public';
  const limit = pickNumber(args, 'limit') ?? 50;
  const searchstructure = pickValue(args, 'searchstructure');
  const queryExpr = serializeQueryStruct(searchstructure, 'matlab');
  // ndiquery(scope, query_obj, 'page', P, 'pageSize', PS) — takes the
  // query OBJECT (not its searchstructure) and returns [b, answer, ...]
  // where answer is a struct with .documents (struct array) + search
  // metadata. Audit 2026-05-18 findings A4/A5.
  return (
    `% Structured NDI Query across one or many datasets.\n` +
    `q = ${queryExpr};\n` +
    `[success, result] = ndi.cloud.api.documents.ndiquery(${formatMatlabValue(scope)}, q, 'pageSize', ${limit});\n` +
    `documents = result.documents;\n` +
    `fprintf('Matched %d document(s)\\n', numel(documents));`
  );
}

function renderAggregateDocuments(args: unknown): string {
  const scope = pickString(args, 'scope') ?? 'public';
  // Default valueField was `data.subject.weight_grams` — that field
  // doesn't exist on the canonical NDI subject schema (audit
  // 2026-05-18 finding C/T3). Default to a field that genuinely
  // exists on vmspikesummary so the snippet works on real data.
  const valueField = pickString(args, 'valueField') ?? 'data.vmspikesummary.mean_firing_rate';
  const groupBy = pickString(args, 'groupBy');
  const maxDocs = pickNumber(args, 'maxDocs') ?? 5000;
  const searchstructure = pickValue(args, 'searchstructure');
  const queryExpr = serializeQueryStruct(searchstructure, 'matlab');
  // ndiqueryAll → struct ARRAY of summaries (no .data). To reach the
  // .data field we follow up with bulkFetch — required for numeric
  // aggregation. Audit 2026-05-18 finding A4/A5.
  // Backend bulkFetch caps at 500 per call; chunk if maxDocs > 500.
  const lines = [
    `% Aggregate a numeric field across documents matching a Query.`,
    `% The chat ran this server-side; the client-side replica uses`,
    `% ndiqueryAll (IDs) → bulkFetch (full data) → manual reduce.`,
    ``,
    `q = ${queryExpr};`,
    `[~, summaries] = ndi.cloud.api.documents.ndiqueryAll(${formatMatlabValue(scope)}, q, 'pageSize', 1000);`,
    `if numel(summaries) > ${maxDocs}; summaries = summaries(1:${maxDocs}); end`,
    ``,
    `% Hydrate full doc bodies in 500-doc chunks (bulkFetch cap).`,
    `docs = struct('id', {}, 'ndiId', {}, 'name', {}, 'className', {}, 'datasetId', {}, 'data', {});`,
    `ids = string({summaries.id});`,
    `% bulkFetch is per-dataset. When scope == 'public' (mixed datasets),`,
    `% group by datasetId first; otherwise call once.`,
    `byDataset = struct();`,
    `for i = 1:numel(summaries)`,
    `    key = char(summaries(i).datasetId);`,
    `    fld = matlab.lang.makeValidName(key);`,
    `    if ~isfield(byDataset, fld); byDataset.(fld) = {}; end`,
    `    byDataset.(fld){end+1} = summaries(i).id; %#ok<AGROW>`,
    `end`,
    `dsFields = fieldnames(byDataset);`,
    `for di = 1:numel(dsFields)`,
    `    keyIds = string(byDataset.(dsFields{di}));`,
    `    % Find the datasetId of any summary in this group:`,
    `    dsId = '';`,
    `    for i = 1:numel(summaries); if matlab.lang.makeValidName(char(summaries(i).datasetId)) == string(dsFields{di}); dsId = summaries(i).datasetId; break; end; end`,
    `    for offset = 1:500:numel(keyIds)`,
    `        chunk = keyIds(offset:min(offset+499, numel(keyIds)));`,
    `        [~, chunkDocs] = ndi.cloud.api.documents.bulkFetch(dsId, chunk);`,
    `        docs = [docs; chunkDocs(:)]; %#ok<AGROW>`,
    `    end`,
    `end`,
    ``,
    `groups = containers.Map('KeyType', 'char', 'ValueType', 'any');`,
    `valuePath = strsplit(${formatMatlabValue(valueField)}, '.');`,
  ];
  if (groupBy) {
    lines.push(`groupPath = strsplit(${formatMatlabValue(groupBy)}, '.');`);
  }
  lines.push(
    ``,
    `for i = 1:numel(docs)`,
    `    d = docs(i);`,
    `    v = d;`,
    `    for k = 1:numel(valuePath); if isfield(v, valuePath{k}); v = v.(valuePath{k}); else; v = NaN; break; end; end`,
    `    if ~isnumeric(v) || ~isfinite(v); continue; end`,
  );
  if (groupBy) {
    lines.push(
      `    g = d;`,
      `    for k = 1:numel(groupPath); if isfield(g, groupPath{k}); g = g.(groupPath{k}); else; g = '(none)'; break; end; end`,
      `    key = char(string(g));`,
    );
  } else {
    lines.push(`    key = 'all';`);
  }
  lines.push(
    `    if ~isKey(groups, key); groups(key) = []; end`,
    `    groups(key) = [groups(key), v];`,
    `end`,
    ``,
    `for key = keys(groups)`,
    `    vs = groups(key{1});`,
    `    fprintf('%s: n=%d mean=%.3f median=%.3f\\n', key{1}, numel(vs), mean(vs), median(vs));`,
    `end`,
  );
  return lines.join('\n');
}

function renderTabularQuery(args: unknown): string {
  const datasetId = pickString(args, 'datasetId') ?? '<dataset-id>';
  const variableNameContains = pickString(args, 'variableNameContains') ?? '';
  const groupBy = pickString(args, 'groupBy');
  const title = pickString(args, 'title');
  // ndiqueryAll returns ID/summary struct array; .data lives only on
  // bulkFetch results. Audit 2026-05-18 finding A4/A5.
  const lines = [
    `% Aggregate an ontologyTableRow into per-group statistics.`,
    `% The NDI Ask chat called a custom backend endpoint; this is the`,
    `% closest user-side equivalent: ndiqueryAll (IDs) → bulkFetch (data) → reduce.`,
    ``,
    `q1 = ndi.query('', 'isa', 'ontologyTableRow');`,
    `q2 = ndi.query('ontologyTableRow.variableNames', 'contains_string', ${formatMatlabValue(variableNameContains)});`,
    `q = q1 & q2;`,
    `[~, summaries] = ndi.cloud.api.documents.ndiqueryAll(${formatMatlabValue(datasetId)}, q, 'pageSize', 1000);`,
    `% Hydrate full bodies in 500-doc chunks (bulkFetch cap).`,
    `rows = struct('id', {}, 'ndiId', {}, 'name', {}, 'className', {}, 'datasetId', {}, 'data', {});`,
    `ids = string({summaries.id});`,
    `for offset = 1:500:numel(ids)`,
    `    chunk = ids(offset:min(offset+499, numel(ids)));`,
    `    [~, chunkDocs] = ndi.cloud.api.documents.bulkFetch(${formatMatlabValue(datasetId)}, chunk);`,
    `    rows = [rows; chunkDocs(:)]; %#ok<AGROW>`,
    `end`,
    ``,
    `% Flatten the ontologyTableRow body into a struct array for analysis.`,
    `bodies = arrayfun(@(r) r.data.ontologyTableRow, rows, 'UniformOutput', false);`,
  ];
  if (groupBy) {
    lines.push(
      ``,
      `% groupBy is a substring match against column names — mirror the backend logic.`,
      `groupHint = lower(${formatMatlabValue(groupBy)});`,
      `% TODO: pick the right column key by substring-matching against`,
      `% fieldnames(bodies{1}). Then compute mean/median per group with`,
      `% accumarray or findgroups.`,
    );
  }
  if (title) {
    lines.push(``, `% Chart title used in the chat: ${oneLine(title)}`);
  }
  return lines.join('\n');
}

function renderFetchSignal(args: unknown): string {
  const datasetId = pickString(args, 'datasetId') ?? '<dataset-id>';
  const docId = pickString(args, 'docId') ?? '<doc-id>';
  const downsample = pickNumber(args, 'downsample') ?? 2000;
  const t0 = pickNumber(args, 't0');
  const t1 = pickNumber(args, 't1');
  const file = pickString(args, 'file');

  const lines = [
    `% Pull a downsampled timeseries from an NDI binary document.`,
    `% NDI-matlab handles binary files through the ndi.daq.reader hierarchy;`,
    `% the typical flow is: fetch the doc, locate its file ref, download`,
    `% bytes via getFile, then decode with the matching daq reader.`,
    ``,
    `[~, doc] = ndi.cloud.api.documents.getDocument(${formatMatlabValue(datasetId)}, ${formatMatlabValue(docId)});`,
  ];
  if (file) {
    lines.push(`% Chat selected file: ${oneLine(file)}`);
  }
  lines.push(
    `% TODO: choose the right file ref (typically the largest .nbf / .vhsb)`,
    `% from doc.files, then:`,
    `%   [~, localPath] = ndi.cloud.api.files.getFile(${formatMatlabValue(datasetId)}, '<file-id>');`,
    `%   reader    = ndi.daq.reader.<format>();`,
    `%   data      = reader.readchannels_epochsamples(...);`,
    `% Downsample to ${downsample} points per channel before plotting.`,
  );
  if (t0 !== null || t1 !== null) {
    lines.push(
      `% Time window used by the chat: t0=${t0 ?? 'NaN'}, t1=${t1 ?? 'NaN'} (seconds).`,
    );
  }
  return lines.join('\n');
}

function renderWalkProvenance(args: unknown): string {
  const datasetId = pickString(args, 'datasetId') ?? '<dataset-id>';
  const docId = pickString(args, 'docId') ?? '<doc-id>';
  const maxDepth = pickNumber(args, 'maxDepth') ?? 3;
  return (
    `% Walk the depends_on graph from a starting document.\n` +
    `function lineage = walkProvenance(datasetId, docId, maxDepth)\n` +
    `    seen = containers.Map();\n` +
    `    lineage = {};\n` +
    `    stack = {struct('id', docId, 'depth', 0)};\n` +
    `    while ~isempty(stack)\n` +
    `        cur = stack{end}; stack(end) = [];\n` +
    `        if cur.depth > maxDepth || isKey(seen, cur.id); continue; end\n` +
    `        seen(cur.id) = true;\n` +
    `        [~, doc] = ndi.cloud.api.documents.getDocument(datasetId, cur.id);\n` +
    `        lineage{end+1} = doc; %#ok<AGROW>\n` +
    `        if isfield(doc, 'depends_on') && iscell(doc.depends_on)\n` +
    `            for k = 1:numel(doc.depends_on)\n` +
    `                edge = doc.depends_on{k};\n` +
    `                if isfield(edge, 'value')\n` +
    `                    stack{end+1} = struct('id', edge.value, 'depth', cur.depth + 1); %#ok<AGROW>\n` +
    `                end\n` +
    `            end\n` +
    `        end\n` +
    `    end\n` +
    `end\n` +
    `\n` +
    `lineage = walkProvenance(${formatMatlabValue(datasetId)}, ${formatMatlabValue(docId)}, ${maxDepth});\n` +
    `fprintf('Walked %d document(s)\\n', numel(lineage));`
  );
}

function renderLookupOntology(args: unknown): string {
  const term = pickString(args, 'term') ?? 'CL:0000540';
  return (
    `% Resolve an ontology CURIE to its name + definition.\n` +
    `% TODO: NDI-matlab's ontology lookup wrapper is in flux — until a\n` +
    `% stable function name lands, call the HTTP endpoint directly:\n` +
    `% result = webread(sprintf('https://api.ndi-cloud.com/api/ontology/lookup?term=%s', urlencode(${formatMatlabValue(term)})));`
  );
}

// a834 P1 #C-1 (2026-05-14) — fetch_image snippet.
function renderFetchImage(args: unknown): string {
  const datasetId = pickString(args, 'datasetId') ?? '<dataset-id>';
  const docId = pickString(args, 'docId') ?? '<doc-id>';
  const frame = pickNumber(args, 'frame') ?? 0;
  const title = pickString(args, 'title');
  // Load a 2D image binary via NDI-matlab's openbinarydoc, decode
  // with imread (TIFF / PNG / JPEG handled natively), display via
  // imshow. See ndi-matlab +ndi/+database/openbinarydoc.m.
  const lines = [
    `% Pull a 2D image from an NDI binary document (TIFF / PNG / etc.).`,
    `% Mirrors the chat's image endpoint: open the doc binary, decode,`,
    `% then imshow. Frame ${frame} selected for multi-frame containers.`,
    ``,
    `[~, doc] = ndi.cloud.api.documents.getDocument(${formatMatlabValue(datasetId)}, ${formatMatlabValue(docId)});`,
    `% openbinarydoc is a METHOD on ndi.session/ndi.dataset (NOT a`,
    `% package-level function). The wrapper signature is`,
    `% S.database_openbinarydoc(doc_or_id, filename). Audit 2026-05-18`,
    `% finding A7. Requires an active local session/dataset:`,
    `%   S = ndi.session.dir([], '<localPath>');`,
    `%   fh = S.database_openbinarydoc(${formatMatlabValue(docId)}, '<filename>');`,
    `% Then read via imread on the file path (or the handle's filename).`,
    `img = imread('<path-to-image-binary>');`,
    `if size(img, 3) > 1; img = rgb2gray(img); end`,
    `figure; imshow(img, []);`,
  ];
  if (title) lines.push(`title(${formatMatlabValue(title)});`);
  return lines.join('\n');
}

// a834 P1 #C-1 (2026-05-14) — treatment_timeline snippet.
function renderTreatmentTimeline(args: unknown): string {
  const datasetId = pickString(args, 'datasetId') ?? '<dataset-id>';
  const title = pickString(args, 'title');
  // Pull treatment docs via ndi.query "isa", extract per-subject
  // timing from numericValue, render with patch() — one Y-row per
  // subject. NDI-matlab has no built-in Gantt helper; this is the
  // closest base-MATLAB equivalent.
  const lines = [
    `% Build a Gantt-style timeline of treatment documents.`,
    `% Each treatment doc carries subjectDocumentIdentifier + treatmentName +`,
    `% numericValue ([start, end] when present). We project to (subject,`,
    `% start, dur) tuples and draw one bar per treatment via patch().`,
    `% ndiqueryAll returns ID summaries; bulkFetch hydrates the .data`,
    `% bodies (audit 2026-05-18 finding A4/A5).`,
    ``,
    `q = ndi.query('', 'isa', 'treatment');`,
    `[~, summaries] = ndi.cloud.api.documents.ndiqueryAll(${formatMatlabValue(datasetId)}, q, 'pageSize', 500);`,
    `[~, treatments] = ndi.cloud.api.documents.bulkFetch(${formatMatlabValue(datasetId)}, string({summaries.id}));`,
    `subjects = {};`,
    `bars = {};   % each: [t0, dur, yIdx]`,
    `for i = 1:numel(treatments)`,
    `    body = treatments(i).data.treatment;`,
    `    subj = '(unknown)'; if isfield(body, 'subjectDocumentIdentifier'); subj = body.subjectDocumentIdentifier; end`,
    `    yIdx = find(strcmp(subjects, subj), 1);`,
    `    if isempty(yIdx); subjects{end+1} = subj; yIdx = numel(subjects); end %#ok<AGROW>`,
    `    nv = []; if isfield(body, 'numericValue'); nv = body.numericValue; end`,
    `    if numel(nv) >= 2; t0 = nv(1); dur = nv(2) - nv(1); else; t0 = i; dur = 1; end`,
    `    bars{end+1} = [t0, dur, yIdx]; %#ok<AGROW>`,
    `end`,
    `figure; hold on;`,
    `for k = 1:numel(bars); b = bars{k}; patch([b(1) b(1)+b(2) b(1)+b(2) b(1)], [b(3)-0.4 b(3)-0.4 b(3)+0.4 b(3)+0.4], [0.3 0.6 0.9]); end`,
    `yticks(1:numel(subjects)); yticklabels(subjects);`,
  ];
  if (title) lines.push(`title(${formatMatlabValue(title)});`);
  return lines.join('\n');
}

// a834 P1 #C-1 (2026-05-14) — fetch_spike_summary snippet.
function renderFetchSpikeSummary(args: unknown): string {
  const datasetId = pickString(args, 'datasetId') ?? '<dataset-id>';
  const unitDocId = pickString(args, 'unitDocId');
  const unitNameMatch = pickString(args, 'unitNameMatch');
  const kind = pickString(args, 'kind') ?? 'raster';
  const maxUnits = pickNumber(args, 'maxUnits') ?? 10;
  // Pull vmspikesummary docs and read data.vmspikesummary.spike_times.
  // NDI-matlab exposes the doc class via ndi.cloud.api.documents.ndiqueryAll;
  // raster uses plot with 'Marker', '|', ISI uses histogram.
  const lines = [
    `% Pull spike-train data from vmspikesummary documents and render a`,
    `% raster (or ISI histogram). Spike times live at`,
    `% data.vmspikesummary.spike_times (seconds).`,
    ``,
  ];
  if (unitDocId) {
    // getDocument returns [b, answer, ...] — pass the answer onward.
    lines.push(
      `[~, doc] = ndi.cloud.api.documents.getDocument(${formatMatlabValue(datasetId)}, ${formatMatlabValue(unitDocId)});`,
      `docs = doc;  % single-element struct so the loop below works uniformly`,
    );
  } else {
    lines.push(`q = ndi.query('', 'isa', 'vmspikesummary');`);
    if (unitNameMatch) {
      lines.push(
        `q = q & ndi.query('vmspikesummary.name', 'contains_string', ${formatMatlabValue(unitNameMatch)});`,
      );
    }
    // ndiqueryAll returns ID summaries; bulkFetch hydrates .data
    // (audit 2026-05-18 finding A4/A5).
    lines.push(
      `[~, summaries] = ndi.cloud.api.documents.ndiqueryAll(${formatMatlabValue(datasetId)}, q, 'pageSize', ${maxUnits});`,
      `if numel(summaries) > ${maxUnits}; summaries = summaries(1:${maxUnits}); end`,
      `[~, docs] = ndi.cloud.api.documents.bulkFetch(${formatMatlabValue(datasetId)}, string({summaries.id}));`,
    );
  }
  lines.push(
    `figure; hold on;`,
    `for k = 1:numel(docs)`,
    `    body = docs(k).data.vmspikesummary;`,
    `    if ~isfield(body, 'spike_times'); continue; end`,
    `    t = double(body.spike_times);`,
  );
  if (kind === 'isi_histogram') {
    lines.push(
      `    isi_ms = diff(sort(t)) * 1000;`,
      `    histogram(isi_ms, logspace(0, 4, 60)); set(gca, 'XScale', 'log');`,
      `    xlabel('ISI (ms)');`,
    );
  } else {
    lines.push(
      `    plot(t, k * ones(size(t)), '|');  % one row per unit`,
      `end`,
      `xlabel('Time (s)'); ylabel('Unit');`,
    );
  }
  if (kind === 'isi_histogram') lines.push(`end`);
  return lines.join('\n');
}

// PSTH snippet — fetch unit + stimulus docs, align spike times to
// each stimulus onset, bin with histogram + bar, dashed line at x=0.
// NOTE: NDI-matlab's stimulus alignment helpers are in flux (see
// upstream-asks doc); this snippet hand-rolls the alignment to stay
// stable regardless of which wrapper lands first.
function renderPsth(args: unknown): string {
  const datasetId = pickString(args, 'datasetId') ?? '<dataset-id>';
  const unitDocId = pickString(args, 'unitDocId') ?? '<unit-doc-id>';
  const stimulusDocId =
    pickString(args, 'stimulusDocId') ?? '<stimulus-doc-id>';
  const t0 = pickNumber(args, 't0') ?? -0.5;
  const t1 = pickNumber(args, 't1') ?? 1.5;
  const binSizeMs = pickNumber(args, 'binSizeMs') ?? 20;
  const title = pickString(args, 'title');
  const lines = [
    `% Peri-stimulus time histogram. Pull spike times from the vmspikesummary`,
    `% doc and event times from the stimulus doc, then bin the spikes inside`,
    `% [t0, t1] relative to each stimulus onset.`,
    `% NOTE: NDI-matlab's stimulus alignment helpers are still being wired;`,
    `% this snippet hand-rolls the alignment so it works regardless of which`,
    `% upstream wrapper lands first (see upstream-asks for context).`,
    ``,
    `[~, unitDoc] = ndi.cloud.api.documents.getDocument(${formatMatlabValue(datasetId)}, ${formatMatlabValue(unitDocId)});`,
    `[~, stimDoc] = ndi.cloud.api.documents.getDocument(${formatMatlabValue(datasetId)}, ${formatMatlabValue(stimulusDocId)});`,
    ``,
    `% Spike times live at data.vmspikesummary.spike_times (seconds).`,
    `if isfield(unitDoc.data.vmspikesummary, 'spike_times')`,
    `    spikeTimes = double(unitDoc.data.vmspikesummary.spike_times);`,
    `elseif isfield(unitDoc.data.vmspikesummary, 'sample_times')`,
    `    spikeTimes = double(unitDoc.data.vmspikesummary.sample_times);`,
    `else`,
    `    spikeTimes = [];`,
    `end`,
    ``,
    `% Event times: stimulus_presentation carries time_started or stim_time.`,
    `stim = stimDoc.data.stimulus_presentation;`,
    `if isfield(stim, 'time_started')`,
    `    events = double(stim.time_started);`,
    `elseif isfield(stim, 'stim_time')`,
    `    events = double(stim.stim_time);`,
    `else`,
    `    events = [];`,
    `end`,
    ``,
    `t0 = ${t0}; t1 = ${t1};`,
    `binSizeS = ${binSizeMs} / 1000;`,
    `edges = t0:binSizeS:t1;`,
    `centers = edges(1:end-1) + binSizeS/2;`,
    ``,
    `% Align spikes to each event onset and collect those inside [t0, t1].`,
    `aligned = [];`,
    `for k = 1:numel(events)`,
    `    rel = spikeTimes - events(k);`,
    `    aligned = [aligned; rel(rel >= t0 & rel <= t1)]; %#ok<AGROW>`,
    `end`,
    `counts = histcounts(aligned, edges);`,
    `nTrials = max(1, numel(events));`,
    `meanRateHz = counts / (nTrials * binSizeS);`,
    ``,
    `figure; bar(centers, meanRateHz, 1, 'FaceColor', [0.01 0.52 0.78]);`,
    `% Dashed vertical line at x=0 marks stimulus onset.`,
    `hold on; xline(0, '--r', 'LineWidth', 1);`,
    `xlabel('Time relative to stimulus (s)'); ylabel('Firing rate (Hz)');`,
  ];
  if (title) lines.push(`title(${formatMatlabValue(title)});`);
  return lines.join('\n');
}
