/**
 * Python snippet generator for the "Show code" button.
 *
 * Maps each recorded NDI Ask tool call to its NDI-python equivalent
 * so a PI / grad student can paste the snippet into a Jupyter
 * notebook and reproduce the analysis the chat just walked through.
 *
 * The function names referenced here mirror the public surface of
 * `ndi.cloud.api.*` (datasets, documents, files) at the head of the
 * NDI-python repo. When the right SDK function is uncertain, the
 * snippet emits a `# TODO` comment with a pointer rather than
 * inventing an API — the user will refine in v2.
 *
 * Output shape: ONE Python file as a string. Top-level imports,
 * then sequential statements per tool call. Each tool emits a
 * short comment header so the snippet reads top-to-bottom like a
 * notebook.
 */
import type { RecordedToolCall } from './types';
import {
  formatPythonValue,
  pickNumber,
  pickString,
  pickValue,
  serializeQueryStruct,
} from './utils';

export interface PythonSnippetOptions {
  /** The user's original question. Rendered in the file header so the
   *  snippet is self-documenting when shared. */
  question?: string;
  /** ISO timestamp for the file header. Defaults to now. */
  timestamp?: string;
  /** URL of the chat the snippet was exported from, for traceability. */
  chatUrl?: string;
}

/**
 * Top-of-file imports + module-level setup. Kept minimal — we only
 * import the high-level `ndi` namespace. The Python SDK re-exports
 * `ndi.cloud`, `ndi.query`, `ndi.ontology` etc. through its
 * `__init__.py`, so this single import covers every snippet we emit.
 */
const PY_HEADER_IMPORTS = `import ndi
import ndi.cloud.api.datasets
import ndi.cloud.api.documents
import ndi.cloud.api.files
import ndi.cloud.filehandler
import ndi.ontology
import ndi.query
`;

/**
 * Build the snippet's banner comment. Shown before any code so a
 * reader can immediately see *what* this script answers.
 */
function header(opts: PythonSnippetOptions): string {
  const now = opts.timestamp ?? new Date().toISOString();
  const lines: string[] = [
    '"""',
    'NDI Ask — reproducible Python snippet.',
    '',
    'Generated by the experimental NDI Ask chat. Each call below ',
    'mirrors a tool the assistant invoked while answering your ',
    'question. You can paste this file into a Jupyter notebook or ',
    'run it as a script after `pip install ndi-python`.',
    '',
  ];
  if (opts.question) {
    lines.push(`Question: ${oneLine(opts.question)}`);
  }
  lines.push(`Generated: ${now}`);
  if (opts.chatUrl) {
    lines.push(`Chat: ${opts.chatUrl}`);
  }
  lines.push('"""');
  return lines.join('\n');
}

/**
 * Collapse a possibly-multi-line user question to a single line so
 * the docstring stays well-formed.
 */
function oneLine(s: string): string {
  return s.replace(/\s+/g, ' ').trim();
}

/**
 * Generate a Python snippet from the recorded tool-call sequence.
 *
 * The output is deterministic — same input → same string — so the
 * snippet diffs cleanly in version control if the user saves it.
 */
export function generatePythonSnippet(
  toolCalls: RecordedToolCall[],
  options: PythonSnippetOptions = {},
): string {
  const blocks: string[] = [];

  blocks.push(header(options));
  blocks.push(PY_HEADER_IMPORTS);

  if (toolCalls.length === 0) {
    blocks.push(
      '# (No tool calls were recorded for this answer — the assistant\n' +
        '# answered from prior context. Nothing to reproduce.)\n',
    );
    return blocks.join('\n');
  }

  toolCalls.forEach((call, index) => {
    blocks.push(renderToolCall(call, index));
  });

  return blocks.join('\n');
}

/**
 * Render one tool call. Each section starts with a numbered comment
 * banner so the user can locate "step 3" both in the chat and in the
 * snippet.
 */
function renderToolCall(call: RecordedToolCall, index: number): string {
  const banner = `# ── Step ${index + 1}: ${call.toolName} ──`;
  const body = renderToolBody(call);
  return `${banner}\n${body}`;
}

/**
 * Dispatch on tool name. Each branch produces idiomatic NDI-python
 * code for that tool. When inputs are missing or unexpected, we still
 * emit *something* runnable — a comment + a best-effort call — so
 * the user can patch it instead of staring at a blank line.
 */
function renderToolBody(call: RecordedToolCall): string {
  const args = call.args ?? {};
  switch (call.toolName) {
    case 'list_published_datasets':
      return renderListPublishedDatasets(args);
    case 'get_dataset':
      return renderGetDataset(args);
    case 'get_dataset_summary':
      return renderGetDatasetSummary(args);
    case 'get_dataset_class_counts':
      return renderGetDatasetClassCounts(args);
    case 'get_facets':
      return renderGetFacets();
    case 'semantic_search_datasets':
      return renderSemanticSearchDatasets(args, call.result);
    case 'query_documents':
      return renderQueryDocuments(args);
    case 'ndi_query':
      return renderNdiQuery(args);
    case 'aggregate_documents':
      return renderAggregateDocuments(args);
    case 'tabular_query':
      return renderTabularQuery(args);
    case 'fetch_signal':
      return renderFetchSignal(args);
    // a834 P1 #C-1 (2026-05-14) — chart-tool snippets added below.
    case 'fetch_image':
      return renderFetchImage(args);
    case 'treatment_timeline':
      return renderTreatmentTimeline(args);
    case 'fetch_spike_summary':
      return renderFetchSpikeSummary(args);
    case 'psth':
      return renderPsth(args);
    case 'walk_provenance':
      return renderWalkProvenance(args);
    case 'lookup_ontology':
      return renderLookupOntology(args);
    default:
      return (
        `# TODO: no NDI-python mapping known for "${call.toolName}".\n` +
        `# Arguments captured from the chat:\n` +
        `args = ${formatPythonValue(args)}\n`
      );
  }
}

// ── per-tool emitters ────────────────────────────────────────────────

function renderListPublishedDatasets(args: unknown): string {
  const page = pickNumber(args, 'page') ?? 1;
  const pageSize = pickNumber(args, 'pageSize') ?? 20;
  const query = pickString(args, 'query');
  const lines = [
    `# Browse the public NDI catalog. Returns a page of dataset records.`,
  ];
  if (query) {
    lines.push(
      `published = ndi.cloud.api.datasets.getPublished(`,
      `    page=${page}, page_size=${pageSize}, query=${formatPythonValue(query)}`,
      `)`,
    );
  } else {
    lines.push(
      `published = ndi.cloud.api.datasets.getPublished(page=${page}, page_size=${pageSize})`,
    );
  }
  lines.push(`print(f"Total datasets: {published.get('totalNumber', 0)}")`);
  return lines.join('\n') + '\n';
}

function renderGetDataset(args: unknown): string {
  const id = pickString(args, 'id') ?? '<dataset-id>';
  return (
    `# Fetch the full record for a single dataset.\n` +
    `dataset = ndi.cloud.api.datasets.getDataset(${formatPythonValue(id)})\n` +
    `print(dataset.get('name'), '—', dataset.get('description'))\n`
  );
}

function renderGetDatasetSummary(args: unknown): string {
  const id = pickString(args, 'id') ?? '<dataset-id>';
  return (
    `# Fetch a compact summary (counts + key metadata) for one dataset.\n` +
    `# TODO: NDI-python's compact summary endpoint isn't yet exposed as a\n` +
    `# dedicated function; use getDataset() for the full record and read\n` +
    `# the count fields directly.\n` +
    `summary = ndi.cloud.api.datasets.getDataset(${formatPythonValue(id)})\n`
  );
}

function renderGetDatasetClassCounts(args: unknown): string {
  const id = pickString(args, 'id') ?? '<dataset-id>';
  return (
    `# Count documents per class for one dataset.\n` +
    `counts = ndi.cloud.api.documents.documentClassCounts(${formatPythonValue(id)})\n` +
    `for cls, n in counts.items():\n` +
    `    print(f"{cls}: {n}")\n`
  );
}

function renderGetFacets(): string {
  return (
    `# Cross-catalog facets (species / brain regions / strains).\n` +
    `# TODO: no public NDI-python wrapper for /api/facets yet — call the\n` +
    `# HTTP endpoint directly via the cloud client until one lands.\n` +
    `client = ndi.cloud.filehandler.get_or_create_cloud_client()\n` +
    `facets = client.get("/api/facets")\n`
  );
}

function renderSemanticSearchDatasets(args: unknown, result: unknown): string {
  // RAG isn't reproducible in user code — the embedding index lives
  // in the chat's server. We emit a comment that just lists the
  // dataset IDs that came back, so the snippet has SOMETHING the
  // user can pivot on (e.g. drop into getDataset).
  const query = pickString(args, 'query') ?? '';
  const lines = [
    `# Semantic search isn't reproducible in user code — the embedding`,
    `# index lives behind the NDI Ask chat. The IDs below are what the`,
    `# chat found for: ${oneLine(query)}`,
  ];
  const results = pickValue(result, 'results');
  if (Array.isArray(results)) {
    for (const r of results) {
      const id = pickString(r, 'id');
      const name = pickString(r, 'name');
      if (id) lines.push(`# - ${id}${name ? ` — ${name}` : ''}`);
    }
  }
  lines.push(
    `# Use one of these IDs as input to getDataset() / documentClassCounts().`,
  );
  return lines.join('\n') + '\n';
}

function renderQueryDocuments(args: unknown): string {
  const datasetId = pickString(args, 'datasetId') ?? '<dataset-id>';
  const className = pickString(args, 'className') ?? 'subject';
  const limit = pickNumber(args, 'limit') ?? 10;
  return (
    `# Pull all documents of a given class inside one dataset.\n` +
    `q = ndi.query.ndi_query.from_search("", "isa", ${formatPythonValue(className)})\n` +
    `docs = ndi.cloud.api.documents.ndiqueryAll(\n` +
    `    ${formatPythonValue(datasetId)}, q.search_structure, page_size=${limit}\n` +
    `)\n` +
    `print(f"Found {len(docs)} ${className} document(s)")\n`
  );
}

function renderNdiQuery(args: unknown): string {
  const scope = pickString(args, 'scope') ?? 'public';
  const limit = pickNumber(args, 'limit') ?? 50;
  const searchstructure = pickValue(args, 'searchstructure');
  const queryExpr = serializeQueryStruct(searchstructure, 'python');
  return (
    `# Structured NDI Query across one or many datasets.\n` +
    `q = ${queryExpr}\n` +
    `result = ndi.cloud.api.documents.ndiquery(\n` +
    `    ${formatPythonValue(scope)}, q.search_structure, page_size=${limit}\n` +
    `)\n` +
    `documents = result.get("documents", [])\n` +
    `print(f"Matched {len(documents)} document(s) (total {result.get('totalItems', len(documents))})")\n`
  );
}

function renderAggregateDocuments(args: unknown): string {
  const scope = pickString(args, 'scope') ?? 'public';
  const valueField = pickString(args, 'valueField') ?? 'data.subject.weight_grams';
  const groupBy = pickString(args, 'groupBy');
  const maxDocs = pickNumber(args, 'maxDocs') ?? 5000;
  const searchstructure = pickValue(args, 'searchstructure');
  const queryExpr = serializeQueryStruct(searchstructure, 'python');

  const lines = [
    `# Compute summary statistics over a Query-matched set of documents.`,
    `# Server-side aggregation is deterministic; we replicate it client-side`,
    `# here with numpy / statistics so the user can re-run on fresh data.`,
    `import math`,
    `import statistics`,
    `from typing import Any`,
    ``,
    `q = ${queryExpr}`,
    `docs = ndi.cloud.api.documents.ndiqueryAll(`,
    `    ${formatPythonValue(scope)}, q.search_structure, page_size=1000`,
    `)`,
    `docs = list(docs)[:${maxDocs}]`,
    ``,
    `def _read(doc: dict[str, Any], path: str) -> Any:`,
    `    cur: Any = doc`,
    `    for seg in path.split("."):`,
    `        if not isinstance(cur, dict): return None`,
    `        cur = cur.get(seg)`,
    `    return cur`,
    ``,
    `groups: dict[str, list[float]] = {}`,
    `for d in docs:`,
    `    raw = _read(d, ${formatPythonValue(valueField)})`,
    `    if not isinstance(raw, (int, float)) or math.isnan(float(raw)):`,
    `        continue`,
  ];
  if (groupBy) {
    lines.push(
      `    key = _read(d, ${formatPythonValue(groupBy)})`,
      `    key = str(key) if key is not None else "(none)"`,
    );
  } else {
    lines.push(`    key = "all"`);
  }
  lines.push(
    `    groups.setdefault(key, []).append(float(raw))`,
    ``,
    `for k, vs in groups.items():`,
    `    print(f"{k}: n={len(vs)} mean={statistics.fmean(vs):.3f} median={statistics.median(vs):.3f}")`,
  );
  return lines.join('\n') + '\n';
}

function renderTabularQuery(args: unknown): string {
  const datasetId = pickString(args, 'datasetId') ?? '<dataset-id>';
  const variableNameContains = pickString(args, 'variableNameContains') ?? '';
  const groupBy = pickString(args, 'groupBy');
  const title = pickString(args, 'title');

  // The cleanest NDI-python idiom for this is an ontologyTableRow
  // ndi_query plus a pandas group-by on the resulting frame. We
  // emit that pattern even though the chat's tabular_query backend
  // does a richer aggregation — this gets the user 80% of the way
  // there with shippable Python.
  const lines = [
    `# Aggregate an ontologyTableRow into per-group statistics ready for`,
    `# a violin / jitter plot. The chat's tabular_query tool runs the same`,
    `# logic server-side; this is the user-side replica.`,
    `import pandas as pd`,
    ``,
    `q = ndi.query.ndi_query.from_search("", "isa", "ontologyTableRow")`,
    `q = q & ndi.query.ndi_query.from_search("ontologyTableRow.variableNames", "contains_string", ${formatPythonValue(variableNameContains)})`,
    `rows = ndi.cloud.api.documents.ndiqueryAll(`,
    `    ${formatPythonValue(datasetId)}, q.search_structure, page_size=1000`,
    `)`,
    `df = pd.DataFrame([r.get("data", {}).get("ontologyTableRow", {}) for r in list(rows)])`,
  ];
  if (groupBy) {
    lines.push(
      ``,
      `# Group label substring-match against column keys (mirrors backend).`,
      `match = [c for c in df.columns if ${formatPythonValue(groupBy.toLowerCase())} in c.lower()]`,
      `group_col = match[0] if match else None`,
      `value_cols = [c for c in df.columns if pd.api.types.is_numeric_dtype(df[c])]`,
      `if group_col and value_cols:`,
      `    summary = df.groupby(group_col)[value_cols[0]].agg(["count", "mean", "median", "std", "min", "max"])`,
      `    print(summary)`,
    );
  } else {
    lines.push(
      ``,
      `# No groupBy supplied — collapse to a single summary.`,
      `value_cols = [c for c in df.columns if pd.api.types.is_numeric_dtype(df[c])]`,
      `if value_cols:`,
      `    print(df[value_cols[0]].describe())`,
    );
  }
  if (title) {
    lines.push(``, `# Chart title used in the chat: ${oneLine(title)}`);
  }
  return lines.join('\n') + '\n';
}

function renderFetchSignal(args: unknown): string {
  const datasetId = pickString(args, 'datasetId') ?? '<dataset-id>';
  const docId = pickString(args, 'docId') ?? '<doc-id>';
  const downsample = pickNumber(args, 'downsample') ?? 2000;
  const t0 = pickNumber(args, 't0');
  const t1 = pickNumber(args, 't1');
  const file = pickString(args, 'file');

  const lines = [
    `# Pull a downsampled timeseries from an NDI binary document.`,
    `# The chat called the FastAPI /signal endpoint; the equivalent`,
    `# user-side path is fetch_cloud_file + binary decode.`,
    `doc = ndi.cloud.api.documents.getDocument(`,
    `    ${formatPythonValue(datasetId)}, ${formatPythonValue(docId)}`,
    `)`,
  ];
  if (file) {
    lines.push(`# Chat selected file: ${oneLine(file)}`);
  }
  lines.push(
    `# TODO: pick the right file ref off doc['files'] (typically the`,
    `# largest .nbf / .vhsb), then call ndi.cloud.filehandler.fetch_cloud_file`,
    `# with its NDIC URI to download the raw bytes.`,
    `# local_path = ndi.cloud.filehandler.fetch_cloud_file("<ndic-uri>")`,
    ``,
    `# Downsample target the chat used: ${downsample} points per channel.`,
  );
  if (t0 !== null || t1 !== null) {
    lines.push(
      `# Time window used by the chat: t0=${t0 ?? 'None'}, t1=${t1 ?? 'None'} (seconds).`,
    );
  }
  return lines.join('\n') + '\n';
}

function renderWalkProvenance(args: unknown): string {
  const datasetId = pickString(args, 'datasetId') ?? '<dataset-id>';
  const docId = pickString(args, 'docId') ?? '<doc-id>';
  const maxDepth = pickNumber(args, 'maxDepth') ?? 3;
  return (
    `# Walk the depends_on graph from a starting document.\n` +
    `def walk_provenance(dataset_id: str, doc_id: str, max_depth: int) -> list[dict]:\n` +
    `    """Recursive DFS over depends_on edges. Stops at max_depth."""\n` +
    `    seen: set[str] = set()\n` +
    `    chain: list[dict] = []\n` +
    `    def visit(d_id: str, depth: int) -> None:\n` +
    `        if depth > max_depth or d_id in seen: return\n` +
    `        seen.add(d_id)\n` +
    `        doc = ndi.cloud.api.documents.getDocument(dataset_id, d_id)\n` +
    `        chain.append(doc)\n` +
    `        for edge in (doc.get("depends_on") or []):\n` +
    `            target = edge.get("value")\n` +
    `            if target: visit(target, depth + 1)\n` +
    `    visit(doc_id, 0)\n` +
    `    return chain\n` +
    `\n` +
    `lineage = walk_provenance(\n` +
    `    ${formatPythonValue(datasetId)}, ${formatPythonValue(docId)}, ${maxDepth}\n` +
    `)\n` +
    `for node in lineage:\n` +
    `    print(node.get("document_class", {}).get("class_name"), node.get("id"))\n`
  );
}

function renderLookupOntology(args: unknown): string {
  const term = pickString(args, 'term') ?? 'CL:0000540';
  return (
    `# Resolve an ontology CURIE to its name + definition.\n` +
    `result = ndi.ontology.lookup(${formatPythonValue(term)})\n` +
    `print(result.name, '—', result.definition)\n`
  );
}

// a834 P1 #C-1 (2026-05-14) — fetch_image snippet.
function renderFetchImage(args: unknown): string {
  const datasetId = pickString(args, 'datasetId') ?? '<dataset-id>';
  const docId = pickString(args, 'docId') ?? '<doc-id>';
  const frame = pickNumber(args, 'frame') ?? 0;
  const title = pickString(args, 'title');
  // Open the image-bearing binary doc via NDI-python's session loader,
  // decode the bytes with Pillow (matches the FastAPI backend's
  // Pillow path), and visualize with matplotlib. See ndi-python
  // ndi.database.openbinarydoc + ndi.cloud.api.documents.getDocument.
  const lines = [
    `# Pull a 2D image from an NDI binary document (TIFF / PNG / etc.).`,
    `# Mirrors the chat's /api/datasets/:id/documents/:docId/image path:`,
    `# open the doc binary via NDI-python, decode with Pillow, plot.`,
    `import matplotlib.pyplot as plt`,
    `from PIL import Image`,
    ``,
    `doc = ndi.cloud.api.documents.getDocument(`,
    `    ${formatPythonValue(datasetId)}, ${formatPythonValue(docId)}`,
    `)`,
    `# openbinarydoc returns a file-like handle pointing at the doc's`,
    `# binary file (TIFF / PNG / JPEG / GIF auto-detected by Pillow).`,
    `with ndi.database.openbinarydoc(${formatPythonValue(docId)}) as fh:`,
    `    img = Image.open(fh)`,
    `    img.seek(${frame})  # multi-frame TIFF / animated GIF: pick frame`,
    `    arr = img.convert("F")  # float grayscale; matches the chart backend`,
    `plt.imshow(arr, cmap="gray")`,
    `plt.colorbar()`,
  ];
  if (title) lines.push(`plt.title(${formatPythonValue(title)})`);
  lines.push(`plt.show()`);
  return lines.join('\n') + '\n';
}

// a834 P1 #C-1 (2026-05-14) — treatment_timeline snippet.
function renderTreatmentTimeline(args: unknown): string {
  const datasetId = pickString(args, 'datasetId') ?? '<dataset-id>';
  const title = pickString(args, 'title');
  // Pull every treatment doc inside the dataset via the ndi_query
  // "isa" path, parse start/end from numericValue (the chat's
  // canonical timing source), and render with matplotlib broken_barh.
  // See ndi-python ndi.query + ndi.cloud.api.documents.ndiqueryAll.
  const lines = [
    `# Build a Gantt-style timeline of treatment documents across subjects.`,
    `# Each treatment doc carries {subjectDocumentIdentifier, treatmentName,`,
    `# numericValue: [start, end]?}. We project to (subject, treatment, start,`,
    `# end) rows then plot with matplotlib broken_barh — one row per subject.`,
    `import matplotlib.pyplot as plt`,
    ``,
    `q = ndi.query.ndi_query.from_search("", "isa", "treatment")`,
    `treatments = ndi.cloud.api.documents.ndiqueryAll(`,
    `    ${formatPythonValue(datasetId)}, q.search_structure, page_size=500`,
    `)`,
    `rows: dict[str, list[tuple[float, float, str]]] = {}`,
    `for i, doc in enumerate(treatments):`,
    `    body = (doc.get("data", {}) or {}).get("treatment", {}) or {}`,
    `    subject = body.get("subjectDocumentIdentifier") or "(unknown)"`,
    `    name = body.get("treatmentName") or body.get("stringValue") or "treatment"`,
    `    nv = body.get("numericValue") or []`,
    `    if isinstance(nv, list) and len(nv) >= 2:`,
    `        t0, t1 = float(nv[0]), float(nv[1])`,
    `    else:`,
    `        t0, t1 = float(i), float(i) + 1  # ordinal fallback`,
    `    rows.setdefault(subject, []).append((t0, t1 - t0, name))`,
    `fig, ax = plt.subplots(figsize=(10, max(2, 0.4 * len(rows))))`,
    `for y, (subject, bars) in enumerate(rows.items()):`,
    `    ax.broken_barh([(s, w) for s, w, _ in bars], (y - 0.4, 0.8))`,
    `ax.set_yticks(range(len(rows)))`,
    `ax.set_yticklabels(list(rows.keys()))`,
  ];
  if (title) lines.push(`ax.set_title(${formatPythonValue(title)})`);
  lines.push(`plt.show()`);
  return lines.join('\n') + '\n';
}

// a834 P1 #C-1 (2026-05-14) — fetch_spike_summary snippet.
function renderFetchSpikeSummary(args: unknown): string {
  const datasetId = pickString(args, 'datasetId') ?? '<dataset-id>';
  const unitDocId = pickString(args, 'unitDocId');
  const unitNameMatch = pickString(args, 'unitNameMatch');
  const kind = pickString(args, 'kind') ?? 'raster';
  const maxUnits = pickNumber(args, 'maxUnits') ?? 10;
  // Pull vmspikesummary docs (either a specific unit or by name match),
  // read data.vmspikesummary.spike_times, then render either a raster
  // (matplotlib eventplot) or an ISI histogram. Spike-time field path
  // matches the chat backend's extractor.
  const lines = [
    `# Pull spike-train data from vmspikesummary documents and render`,
    `# the same raster / ISI histogram the chat showed. Spike times live`,
    `# at data.vmspikesummary.spike_times (seconds).`,
    `import matplotlib.pyplot as plt`,
    `import numpy as np`,
    ``,
  ];
  if (unitDocId) {
    lines.push(
      `# Direct fetch of one unit:`,
      `docs = [ndi.cloud.api.documents.getDocument(`,
      `    ${formatPythonValue(datasetId)}, ${formatPythonValue(unitDocId)}`,
      `)]`,
    );
  } else {
    lines.push(
      `q = ndi.query.ndi_query.from_search("", "isa", "vmspikesummary")`,
    );
    if (unitNameMatch) {
      lines.push(
        `q = q & ndi.query.ndi_query.from_search(`,
        `    "vmspikesummary.name", "contains_string", ${formatPythonValue(unitNameMatch)}`,
        `)`,
      );
    }
    lines.push(
      `docs = list(ndi.cloud.api.documents.ndiqueryAll(`,
      `    ${formatPythonValue(datasetId)}, q.search_structure, page_size=${maxUnits}`,
      `))[:${maxUnits}]`,
    );
  }
  lines.push(
    `trains = [d.get("data", {}).get("vmspikesummary", {}).get("spike_times") or []`,
    `          for d in docs]`,
    `trains = [np.asarray(t, dtype=float) for t in trains if len(t) > 0]`,
  );
  if (kind === 'isi_histogram') {
    lines.push(
      `isi_ms = np.concatenate([np.diff(np.sort(t)) for t in trains]) * 1000`,
      `plt.hist(isi_ms, bins=np.logspace(0, 4, 60)); plt.xscale("log")`,
      `plt.xlabel("ISI (ms)")`,
    );
  } else {
    lines.push(`plt.eventplot(trains); plt.xlabel("Time (s)")`);
  }
  lines.push(`plt.show()`);
  return lines.join('\n') + '\n';
}

// PSTH snippet — pulls vmspikesummary spike times + stimulus_presentation
// event times, computes per-trial spike alignment, bins with
// numpy.histogram, plots with matplotlib.bar + a dashed vertical line
// at x=0 marking stimulus onset.
function renderPsth(args: unknown): string {
  const datasetId = pickString(args, 'datasetId') ?? '<dataset-id>';
  const unitDocId = pickString(args, 'unitDocId') ?? '<unit-doc-id>';
  const stimulusDocId =
    pickString(args, 'stimulusDocId') ?? '<stimulus-doc-id>';
  const t0 = pickNumber(args, 't0') ?? -0.5;
  const t1 = pickNumber(args, 't1') ?? 1.5;
  const binSizeMs = pickNumber(args, 'binSizeMs') ?? 20;
  const title = pickString(args, 'title');
  const lines = [
    `# Peri-stimulus time histogram. Pull spike times from the vmspikesummary`,
    `# doc and event times from the stimulus_presentation doc, then bin the`,
    `# spikes inside a [t0, t1] window relative to each stimulus onset.`,
    `import matplotlib.pyplot as plt`,
    `import numpy as np`,
    ``,
    `unit_doc = ndi.cloud.api.documents.getDocument(`,
    `    ${formatPythonValue(datasetId)}, ${formatPythonValue(unitDocId)}`,
    `)`,
    `stim_doc = ndi.cloud.api.documents.getDocument(`,
    `    ${formatPythonValue(datasetId)}, ${formatPythonValue(stimulusDocId)}`,
    `)`,
    ``,
    `# Spike-time field path matches the chat backend's extractor: try`,
    `# spike_times, then sample_times.`,
    `vm = (unit_doc.get("data", {}) or {}).get("vmspikesummary", {}) or {}`,
    `spike_times = vm.get("spike_times") or vm.get("sample_times") or []`,
    `spike_times = np.asarray(spike_times, dtype=float)`,
    ``,
    `# Event times: stimulus_presentation typically carries time_started`,
    `# or stim_time; pick whichever the chat backend resolved to.`,
    `stim = (stim_doc.get("data", {}) or {}).get("stimulus_presentation", {}) or {}`,
    `event_times = (stim.get("time_started") or stim.get("stim_time") or [])`,
    `event_times = np.asarray(event_times, dtype=float)`,
    ``,
    `# Bin edges in seconds. Bin size in ms → seconds via /1000.`,
    `t0, t1 = ${t0}, ${t1}`,
    `bin_size_s = ${binSizeMs} / 1000.0`,
    `edges = np.arange(t0, t1 + bin_size_s, bin_size_s)`,
    `centers = (edges[:-1] + edges[1:]) / 2`,
    ``,
    `# Per-trial alignment: shift spike times by each event onset and`,
    `# collect those falling inside [t0, t1].`,
    `aligned = []`,
    `for onset in event_times:`,
    `    rel = spike_times - onset`,
    `    aligned.append(rel[(rel >= t0) & (rel <= t1)])`,
    `flat = np.concatenate(aligned) if aligned else np.array([])`,
    ``,
    `counts, _ = np.histogram(flat, bins=edges)`,
    `# Normalize counts → firing rate (Hz): divide by (n_trials × bin_size_s).`,
    `n_trials = max(1, len(event_times))`,
    `mean_rate_hz = counts / (n_trials * bin_size_s)`,
    ``,
    `fig, ax = plt.subplots(figsize=(8, 4))`,
    `ax.bar(centers, mean_rate_hz, width=bin_size_s, color="#0284c7")`,
    `# Dashed vertical line at x=0 marks stimulus onset — what visually`,
    `# turns a bar chart into a PSTH.`,
    `ax.axvline(0, color="#dc2626", linestyle="--", linewidth=1)`,
    `ax.set_xlabel("Time relative to stimulus (s)")`,
    `ax.set_ylabel("Firing rate (Hz)")`,
  ];
  if (title) lines.push(`ax.set_title(${formatPythonValue(title)})`);
  lines.push(`plt.show()`);
  return lines.join('\n') + '\n';
}
