/**
 * MATLAB snippet generator for the "Show code" button.
 *
 * Mirrors `python.ts` but targets the NDI-matlab toolbox. Function
 * names map to MATLAB's `+ndi/+cloud/+api/{datasets,documents,files}`
 * packages exactly as they exist on the head of NDI-matlab.
 *
 * Output shape: ONE `.m` file as a string. A leading comment banner,
 * then one section per tool call. Sections use the MATLAB section
 * marker (`%%`) so the user can step through with "Run Section" in
 * the MATLAB editor.
 *
 * Wherever the user-side MATLAB API is uncertain (notably the
 * tabular_query and fetch_signal backends, which were added on the
 * NDI Ask backend before any user-facing wrapper landed), the
 * snippet emits a `% TODO:` comment + a placeholder call. The user
 * can refine; this is meant to be a starting point, not a 1:1
 * server replica.
 */
import type { RecordedToolCall } from './types';
import {
  formatMatlabValue,
  pickNumber,
  pickString,
  pickValue,
  serializeQueryStruct,
} from './utils';

export interface MatlabSnippetOptions {
  question?: string;
  timestamp?: string;
  chatUrl?: string;
}

/**
 * Build the leading comment banner. MATLAB doesn't have a native
 * docstring; we use a `%` comment block. The banner stays inside the
 * single-`%` zone so the editor doesn't fold it as a section.
 */
function header(opts: MatlabSnippetOptions): string {
  const now = opts.timestamp ?? new Date().toISOString();
  const lines: string[] = [
    '% NDI Ask — reproducible MATLAB snippet.',
    '%',
    '% Generated by the experimental NDI Ask chat. Each section below',
    '% mirrors a tool the assistant invoked while answering your question.',
    '% Run section-by-section to reproduce the analysis. Requires the',
    '% NDI-matlab toolbox on the MATLAB path.',
    '%',
  ];
  if (opts.question) {
    lines.push(`% Question: ${oneLine(opts.question)}`);
  }
  lines.push(`% Generated: ${now}`);
  if (opts.chatUrl) {
    lines.push(`% Chat: ${opts.chatUrl}`);
  }
  return lines.join('\n');
}

function oneLine(s: string): string {
  return s.replace(/\s+/g, ' ').trim();
}

export function generateMatlabSnippet(
  toolCalls: RecordedToolCall[],
  options: MatlabSnippetOptions = {},
): string {
  const blocks: string[] = [];
  blocks.push(header(options));

  if (toolCalls.length === 0) {
    blocks.push(
      '\n% (No tool calls were recorded for this answer — the assistant\n' +
        '% answered from prior context. Nothing to reproduce.)',
    );
    return blocks.join('\n') + '\n';
  }

  toolCalls.forEach((call, index) => {
    blocks.push(renderToolCall(call, index));
  });

  return blocks.join('\n') + '\n';
}

function renderToolCall(call: RecordedToolCall, index: number): string {
  const banner = `\n%% Step ${index + 1}: ${call.toolName}`;
  return `${banner}\n${renderToolBody(call)}`;
}

function renderToolBody(call: RecordedToolCall): string {
  const args = call.args ?? {};
  switch (call.toolName) {
    case 'list_published_datasets':
      return renderListPublishedDatasets(args);
    case 'get_dataset':
      return renderGetDataset(args);
    case 'get_dataset_summary':
      return renderGetDatasetSummary(args);
    case 'get_dataset_class_counts':
      return renderGetDatasetClassCounts(args);
    case 'get_facets':
      return renderGetFacets();
    case 'semantic_search_datasets':
      return renderSemanticSearchDatasets(args, call.result);
    case 'query_documents':
      return renderQueryDocuments(args);
    case 'ndi_query':
      return renderNdiQuery(args);
    case 'aggregate_documents':
      return renderAggregateDocuments(args);
    case 'tabular_query':
      return renderTabularQuery(args);
    case 'fetch_signal':
      return renderFetchSignal(args);
    // a834 P1 #C-1 (2026-05-14) — chart-tool snippets added below.
    case 'fetch_image':
      return renderFetchImage(args);
    case 'treatment_timeline':
      return renderTreatmentTimeline(args);
    case 'fetch_spike_summary':
      return renderFetchSpikeSummary(args);
    case 'walk_provenance':
      return renderWalkProvenance(args);
    case 'lookup_ontology':
      return renderLookupOntology(args);
    default:
      return (
        `% TODO: no NDI-matlab mapping known for "${call.toolName}".\n` +
        `% Arguments captured from the chat:\n` +
        `args = ${formatMatlabValue(args)};\n`
      );
  }
}

// ── per-tool emitters ────────────────────────────────────────────────

function renderListPublishedDatasets(args: unknown): string {
  const page = pickNumber(args, 'page') ?? 1;
  const pageSize = pickNumber(args, 'pageSize') ?? 20;
  const query = pickString(args, 'query');
  const lines = [
    `% Browse the public NDI catalog (one page).`,
  ];
  if (query) {
    lines.push(
      `published = ndi.cloud.api.datasets.getPublished('page', ${page}, 'pageSize', ${pageSize}, 'query', ${formatMatlabValue(query)});`,
    );
  } else {
    lines.push(
      `published = ndi.cloud.api.datasets.getPublished('page', ${page}, 'pageSize', ${pageSize});`,
    );
  }
  lines.push(`fprintf('Total datasets: %d\\n', published.totalNumber);`);
  return lines.join('\n');
}

function renderGetDataset(args: unknown): string {
  const id = pickString(args, 'id') ?? '<dataset-id>';
  return (
    `% Fetch the full record for one dataset.\n` +
    `dataset = ndi.cloud.api.datasets.getDataset(${formatMatlabValue(id)});\n` +
    `disp(dataset);`
  );
}

function renderGetDatasetSummary(args: unknown): string {
  const id = pickString(args, 'id') ?? '<dataset-id>';
  return (
    `% Fetch a compact summary for one dataset.\n` +
    `% TODO: NDI-matlab does not yet expose a dedicated summary call;\n` +
    `% use getDataset for the full record and read its count fields.\n` +
    `summary = ndi.cloud.api.datasets.getDataset(${formatMatlabValue(id)});`
  );
}

function renderGetDatasetClassCounts(args: unknown): string {
  const id = pickString(args, 'id') ?? '<dataset-id>';
  return (
    `% Count documents per class for one dataset.\n` +
    `counts = ndi.cloud.api.documents.documentClassCounts(${formatMatlabValue(id)});\n` +
    `disp(counts);`
  );
}

function renderGetFacets(): string {
  return (
    `% Cross-catalog facets (species / brain regions / strains).\n` +
    `% TODO: NDI-matlab does not yet wrap /api/facets; call the HTTP\n` +
    `% endpoint via webread once authentication is configured.\n` +
    `% facets = webread('https://api.ndi-cloud.com/api/facets');`
  );
}

function renderSemanticSearchDatasets(args: unknown, result: unknown): string {
  const query = pickString(args, 'query') ?? '';
  const lines = [
    `% Semantic search is not reproducible in user code — the embedding`,
    `% index lives behind the NDI Ask chat. The IDs below are what the`,
    `% chat returned for: ${oneLine(query)}`,
  ];
  const results = pickValue(result, 'results');
  if (Array.isArray(results)) {
    for (const r of results) {
      const id = pickString(r, 'id');
      const name = pickString(r, 'name');
      if (id) lines.push(`%  - ${id}${name ? ` — ${name}` : ''}`);
    }
  }
  lines.push(
    `% Use one of these IDs with ndi.cloud.api.datasets.getDataset to drill in.`,
  );
  return lines.join('\n');
}

function renderQueryDocuments(args: unknown): string {
  const datasetId = pickString(args, 'datasetId') ?? '<dataset-id>';
  const className = pickString(args, 'className') ?? 'subject';
  const limit = pickNumber(args, 'limit') ?? 10;
  return (
    `% Pull all documents of a given class inside one dataset.\n` +
    `q = ndi.query('', 'isa', ${formatMatlabValue(className)});\n` +
    `result = ndi.cloud.api.documents.ndiqueryAll(${formatMatlabValue(datasetId)}, q.searchstructure, 'pageSize', ${limit});\n` +
    `fprintf('Found %d ${className} document(s)\\n', numel(result));`
  );
}

function renderNdiQuery(args: unknown): string {
  const scope = pickString(args, 'scope') ?? 'public';
  const limit = pickNumber(args, 'limit') ?? 50;
  const searchstructure = pickValue(args, 'searchstructure');
  const queryExpr = serializeQueryStruct(searchstructure, 'matlab');
  return (
    `% Structured NDI Query across one or many datasets.\n` +
    `q = ${queryExpr};\n` +
    `result = ndi.cloud.api.documents.ndiquery(${formatMatlabValue(scope)}, q.searchstructure, 'pageSize', ${limit});\n` +
    `documents = result.documents;\n` +
    `fprintf('Matched %d document(s)\\n', numel(documents));`
  );
}

function renderAggregateDocuments(args: unknown): string {
  const scope = pickString(args, 'scope') ?? 'public';
  const valueField = pickString(args, 'valueField') ?? 'data.subject.weight_grams';
  const groupBy = pickString(args, 'groupBy');
  const maxDocs = pickNumber(args, 'maxDocs') ?? 5000;
  const searchstructure = pickValue(args, 'searchstructure');
  const queryExpr = serializeQueryStruct(searchstructure, 'matlab');

  const lines = [
    `% Aggregate a numeric field across documents matching a Query.`,
    `% The chat ran this server-side; the client-side replica uses`,
    `% ndiqueryAll + a manual reduce.`,
    ``,
    `q = ${queryExpr};`,
    `docs = ndi.cloud.api.documents.ndiqueryAll(${formatMatlabValue(scope)}, q.searchstructure, 'pageSize', 1000);`,
    `if numel(docs) > ${maxDocs}; docs = docs(1:${maxDocs}); end`,
    ``,
    `groups = containers.Map('KeyType', 'char', 'ValueType', 'any');`,
    `valuePath = strsplit(${formatMatlabValue(valueField)}, '.');`,
  ];
  if (groupBy) {
    lines.push(`groupPath = strsplit(${formatMatlabValue(groupBy)}, '.');`);
  }
  lines.push(
    ``,
    `for i = 1:numel(docs)`,
    `    d = docs{i};`,
    `    v = d;`,
    `    for k = 1:numel(valuePath); if isfield(v, valuePath{k}); v = v.(valuePath{k}); else; v = NaN; break; end; end`,
    `    if ~isnumeric(v) || ~isfinite(v); continue; end`,
  );
  if (groupBy) {
    lines.push(
      `    g = d;`,
      `    for k = 1:numel(groupPath); if isfield(g, groupPath{k}); g = g.(groupPath{k}); else; g = '(none)'; break; end; end`,
      `    key = char(string(g));`,
    );
  } else {
    lines.push(`    key = 'all';`);
  }
  lines.push(
    `    if ~isKey(groups, key); groups(key) = []; end`,
    `    groups(key) = [groups(key), v];`,
    `end`,
    ``,
    `for key = keys(groups)`,
    `    vs = groups(key{1});`,
    `    fprintf('%s: n=%d mean=%.3f median=%.3f\\n', key{1}, numel(vs), mean(vs), median(vs));`,
    `end`,
  );
  return lines.join('\n');
}

function renderTabularQuery(args: unknown): string {
  const datasetId = pickString(args, 'datasetId') ?? '<dataset-id>';
  const variableNameContains = pickString(args, 'variableNameContains') ?? '';
  const groupBy = pickString(args, 'groupBy');
  const title = pickString(args, 'title');

  const lines = [
    `% Aggregate an ontologyTableRow into per-group statistics.`,
    `% The NDI Ask chat called a custom backend endpoint; this is the`,
    `% closest user-side equivalent using ndiqueryAll + a table reduce.`,
    ``,
    `q1 = ndi.query('', 'isa', 'ontologyTableRow');`,
    `q2 = ndi.query('ontologyTableRow.variableNames', 'contains_string', ${formatMatlabValue(variableNameContains)});`,
    `q = q1 & q2;`,
    `rows = ndi.cloud.api.documents.ndiqueryAll(${formatMatlabValue(datasetId)}, q.searchstructure, 'pageSize', 1000);`,
    ``,
    `% Flatten the ontologyTableRow body into a struct array for analysis.`,
    `bodies = cellfun(@(r) r.data.ontologyTableRow, rows, 'UniformOutput', false);`,
  ];
  if (groupBy) {
    lines.push(
      ``,
      `% groupBy is a substring match against column names — mirror the backend logic.`,
      `groupHint = lower(${formatMatlabValue(groupBy)});`,
      `% TODO: pick the right column key by substring-matching against`,
      `% fieldnames(bodies{1}). Then compute mean/median per group with`,
      `% accumarray or findgroups.`,
    );
  }
  if (title) {
    lines.push(``, `% Chart title used in the chat: ${oneLine(title)}`);
  }
  return lines.join('\n');
}

function renderFetchSignal(args: unknown): string {
  const datasetId = pickString(args, 'datasetId') ?? '<dataset-id>';
  const docId = pickString(args, 'docId') ?? '<doc-id>';
  const downsample = pickNumber(args, 'downsample') ?? 2000;
  const t0 = pickNumber(args, 't0');
  const t1 = pickNumber(args, 't1');
  const file = pickString(args, 'file');

  const lines = [
    `% Pull a downsampled timeseries from an NDI binary document.`,
    `% NDI-matlab handles binary files through the ndi.daq.reader hierarchy;`,
    `% the typical flow is: fetch the doc, locate its file ref, download`,
    `% bytes via getFile, then decode with the matching daq reader.`,
    ``,
    `doc = ndi.cloud.api.documents.getDocument(${formatMatlabValue(datasetId)}, ${formatMatlabValue(docId)});`,
  ];
  if (file) {
    lines.push(`% Chat selected file: ${oneLine(file)}`);
  }
  lines.push(
    `% TODO: choose the right file ref (typically the largest .nbf / .vhsb)`,
    `% from doc.files, then:`,
    `%   localPath = ndi.cloud.api.files.getFile(${formatMatlabValue(datasetId)}, '<file-id>');`,
    `%   reader    = ndi.daq.reader.<format>();`,
    `%   data      = reader.readchannels_epochsamples(...);`,
    `% Downsample to ${downsample} points per channel before plotting.`,
  );
  if (t0 !== null || t1 !== null) {
    lines.push(
      `% Time window used by the chat: t0=${t0 ?? 'NaN'}, t1=${t1 ?? 'NaN'} (seconds).`,
    );
  }
  return lines.join('\n');
}

function renderWalkProvenance(args: unknown): string {
  const datasetId = pickString(args, 'datasetId') ?? '<dataset-id>';
  const docId = pickString(args, 'docId') ?? '<doc-id>';
  const maxDepth = pickNumber(args, 'maxDepth') ?? 3;
  return (
    `% Walk the depends_on graph from a starting document.\n` +
    `function lineage = walkProvenance(datasetId, docId, maxDepth)\n` +
    `    seen = containers.Map();\n` +
    `    lineage = {};\n` +
    `    stack = {struct('id', docId, 'depth', 0)};\n` +
    `    while ~isempty(stack)\n` +
    `        cur = stack{end}; stack(end) = [];\n` +
    `        if cur.depth > maxDepth || isKey(seen, cur.id); continue; end\n` +
    `        seen(cur.id) = true;\n` +
    `        doc = ndi.cloud.api.documents.getDocument(datasetId, cur.id);\n` +
    `        lineage{end+1} = doc; %#ok<AGROW>\n` +
    `        if isfield(doc, 'depends_on') && iscell(doc.depends_on)\n` +
    `            for k = 1:numel(doc.depends_on)\n` +
    `                edge = doc.depends_on{k};\n` +
    `                if isfield(edge, 'value')\n` +
    `                    stack{end+1} = struct('id', edge.value, 'depth', cur.depth + 1); %#ok<AGROW>\n` +
    `                end\n` +
    `            end\n` +
    `        end\n` +
    `    end\n` +
    `end\n` +
    `\n` +
    `lineage = walkProvenance(${formatMatlabValue(datasetId)}, ${formatMatlabValue(docId)}, ${maxDepth});\n` +
    `fprintf('Walked %d document(s)\\n', numel(lineage));`
  );
}

function renderLookupOntology(args: unknown): string {
  const term = pickString(args, 'term') ?? 'CL:0000540';
  return (
    `% Resolve an ontology CURIE to its name + definition.\n` +
    `% TODO: NDI-matlab's ontology lookup wrapper is in flux — until a\n` +
    `% stable function name lands, call the HTTP endpoint directly:\n` +
    `% result = webread(sprintf('https://api.ndi-cloud.com/api/ontology/lookup?term=%s', urlencode(${formatMatlabValue(term)})));`
  );
}

// a834 P1 #C-1 (2026-05-14) — fetch_image snippet.
function renderFetchImage(args: unknown): string {
  const datasetId = pickString(args, 'datasetId') ?? '<dataset-id>';
  const docId = pickString(args, 'docId') ?? '<doc-id>';
  const frame = pickNumber(args, 'frame') ?? 0;
  const title = pickString(args, 'title');
  // Load a 2D image binary via NDI-matlab's openbinarydoc, decode
  // with imread (TIFF / PNG / JPEG handled natively), display via
  // imshow. See ndi-matlab +ndi/+database/openbinarydoc.m.
  const lines = [
    `% Pull a 2D image from an NDI binary document (TIFF / PNG / etc.).`,
    `% Mirrors the chat's image endpoint: open the doc binary, decode,`,
    `% then imshow. Frame ${frame} selected for multi-frame containers.`,
    ``,
    `doc = ndi.cloud.api.documents.getDocument(${formatMatlabValue(datasetId)}, ${formatMatlabValue(docId)});`,
    `% openbinarydoc returns a file handle to the doc's binary file.`,
    `% Requires an active ndi.session S; uncomment + wire as needed:`,
    `%   S = ndi.session.dir(<localPath>);`,
    `%   fh = ndi.database.openbinarydoc(S, ${formatMatlabValue(docId)});`,
    `% Then read via imread on the file path (or the handle's filename).`,
    `img = imread('<path-to-image-binary>');`,
    `if size(img, 3) > 1; img = rgb2gray(img); end`,
    `figure; imshow(img, []);`,
  ];
  if (title) lines.push(`title(${formatMatlabValue(title)});`);
  return lines.join('\n');
}

// a834 P1 #C-1 (2026-05-14) — treatment_timeline snippet.
function renderTreatmentTimeline(args: unknown): string {
  const datasetId = pickString(args, 'datasetId') ?? '<dataset-id>';
  const title = pickString(args, 'title');
  // Pull treatment docs via ndi.query "isa", extract per-subject
  // timing from numericValue, render with patch() — one Y-row per
  // subject. NDI-matlab has no built-in Gantt helper; this is the
  // closest base-MATLAB equivalent.
  const lines = [
    `% Build a Gantt-style timeline of treatment documents.`,
    `% Each treatment doc carries subjectDocumentIdentifier + treatmentName +`,
    `% numericValue ([start, end] when present). We project to (subject,`,
    `% start, dur) tuples and draw one bar per treatment via patch().`,
    ``,
    `q = ndi.query('', 'isa', 'treatment');`,
    `treatments = ndi.cloud.api.documents.ndiqueryAll(${formatMatlabValue(datasetId)}, q.searchstructure, 'pageSize', 500);`,
    `subjects = {};`,
    `bars = {};   % each: [t0, dur, yIdx]`,
    `for i = 1:numel(treatments)`,
    `    body = treatments{i}.data.treatment;`,
    `    subj = '(unknown)'; if isfield(body, 'subjectDocumentIdentifier'); subj = body.subjectDocumentIdentifier; end`,
    `    yIdx = find(strcmp(subjects, subj), 1);`,
    `    if isempty(yIdx); subjects{end+1} = subj; yIdx = numel(subjects); end %#ok<AGROW>`,
    `    nv = []; if isfield(body, 'numericValue'); nv = body.numericValue; end`,
    `    if numel(nv) >= 2; t0 = nv(1); dur = nv(2) - nv(1); else; t0 = i; dur = 1; end`,
    `    bars{end+1} = [t0, dur, yIdx]; %#ok<AGROW>`,
    `end`,
    `figure; hold on;`,
    `for k = 1:numel(bars); b = bars{k}; patch([b(1) b(1)+b(2) b(1)+b(2) b(1)], [b(3)-0.4 b(3)-0.4 b(3)+0.4 b(3)+0.4], [0.3 0.6 0.9]); end`,
    `yticks(1:numel(subjects)); yticklabels(subjects);`,
  ];
  if (title) lines.push(`title(${formatMatlabValue(title)});`);
  return lines.join('\n');
}

// a834 P1 #C-1 (2026-05-14) — fetch_spike_summary snippet.
function renderFetchSpikeSummary(args: unknown): string {
  const datasetId = pickString(args, 'datasetId') ?? '<dataset-id>';
  const unitDocId = pickString(args, 'unitDocId');
  const unitNameMatch = pickString(args, 'unitNameMatch');
  const kind = pickString(args, 'kind') ?? 'raster';
  const maxUnits = pickNumber(args, 'maxUnits') ?? 10;
  // Pull vmspikesummary docs and read data.vmspikesummary.spike_times.
  // NDI-matlab exposes the doc class via ndi.cloud.api.documents.ndiqueryAll;
  // raster uses plot with 'Marker', '|', ISI uses histogram.
  const lines = [
    `% Pull spike-train data from vmspikesummary documents and render a`,
    `% raster (or ISI histogram). Spike times live at`,
    `% data.vmspikesummary.spike_times (seconds).`,
    ``,
  ];
  if (unitDocId) {
    lines.push(
      `docs = {ndi.cloud.api.documents.getDocument(${formatMatlabValue(datasetId)}, ${formatMatlabValue(unitDocId)})};`,
    );
  } else {
    lines.push(`q = ndi.query('', 'isa', 'vmspikesummary');`);
    if (unitNameMatch) {
      lines.push(
        `q = q & ndi.query('vmspikesummary.name', 'contains_string', ${formatMatlabValue(unitNameMatch)});`,
      );
    }
    lines.push(
      `docs = ndi.cloud.api.documents.ndiqueryAll(${formatMatlabValue(datasetId)}, q.searchstructure, 'pageSize', ${maxUnits});`,
      `if numel(docs) > ${maxUnits}; docs = docs(1:${maxUnits}); end`,
    );
  }
  lines.push(
    `figure; hold on;`,
    `for k = 1:numel(docs)`,
    `    body = docs{k}.data.vmspikesummary;`,
    `    if ~isfield(body, 'spike_times'); continue; end`,
    `    t = double(body.spike_times);`,
  );
  if (kind === 'isi_histogram') {
    lines.push(
      `    isi_ms = diff(sort(t)) * 1000;`,
      `    histogram(isi_ms, logspace(0, 4, 60)); set(gca, 'XScale', 'log');`,
      `    xlabel('ISI (ms)');`,
    );
  } else {
    lines.push(
      `    plot(t, k * ones(size(t)), '|');  % one row per unit`,
      `end`,
      `xlabel('Time (s)'); ylabel('Unit');`,
    );
  }
  if (kind === 'isi_histogram') lines.push(`end`);
  return lines.join('\n');
}
